// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfuse/adminapi/v1/adminapi.proto

package pbadminapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlanTier int32

const (
	PlanTier_FREE       PlanTier = 0
	PlanTier_PRO        PlanTier = 1000
	PlanTier_BUSINESS   PlanTier = 2000
	PlanTier_ENTERPRISE PlanTier = 3000
)

var PlanTier_name = map[int32]string{
	0:    "FREE",
	1000: "PRO",
	2000: "BUSINESS",
	3000: "ENTERPRISE",
}

var PlanTier_value = map[string]int32{
	"FREE":       0,
	"PRO":        1000,
	"BUSINESS":   2000,
	"ENTERPRISE": 3000,
}

func (x PlanTier) String() string {
	return proto.EnumName(PlanTier_name, int32(x))
}

func (PlanTier) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_134ea681c61f9ca0, []int{0}
}

type FeatureName int32

const (
	FeatureName_WORKERS            FeatureName = 0 // Deprecated: Do not use.
	FeatureName_TWILIO             FeatureName = 1 // Deprecated: Do not use.
	FeatureName_ALL                FeatureName = 2
	FeatureName_EXTRA_NETWORKS     FeatureName = 3
	FeatureName_ON_DEMAND_NETWORKS FeatureName = 4
	FeatureName_CUSTOM_WORKERS     FeatureName = 5 // Deprecated: Do not use.
	FeatureName_TOKENMETA          FeatureName = 6
	FeatureName_BLOCKAPI           FeatureName = 7
	FeatureName_INTERNAL_EOSQ      FeatureName = 8
)

var FeatureName_name = map[int32]string{
	0: "WORKERS",
	1: "TWILIO",
	2: "ALL",
	3: "EXTRA_NETWORKS",
	4: "ON_DEMAND_NETWORKS",
	5: "CUSTOM_WORKERS",
	6: "TOKENMETA",
	7: "BLOCKAPI",
	8: "INTERNAL_EOSQ",
}

var FeatureName_value = map[string]int32{
	"WORKERS":            0,
	"TWILIO":             1,
	"ALL":                2,
	"EXTRA_NETWORKS":     3,
	"ON_DEMAND_NETWORKS": 4,
	"CUSTOM_WORKERS":     5,
	"TOKENMETA":          6,
	"BLOCKAPI":           7,
	"INTERNAL_EOSQ":      8,
}

func (x FeatureName) String() string {
	return proto.EnumName(FeatureName_name, int32(x))
}

func (FeatureName) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_134ea681c61f9ca0, []int{1}
}

type ApiKeyUsage int32

const (
	ApiKeyUsage_SERVER ApiKeyUsage = 0
	ApiKeyUsage_WEB    ApiKeyUsage = 1
	ApiKeyUsage_MOBILE ApiKeyUsage = 2
	ApiKeyUsage_WORKER ApiKeyUsage = 3
)

var ApiKeyUsage_name = map[int32]string{
	0: "SERVER",
	1: "WEB",
	2: "MOBILE",
	3: "WORKER",
}

var ApiKeyUsage_value = map[string]int32{
	"SERVER": 0,
	"WEB":    1,
	"MOBILE": 2,
	"WORKER": 3,
}

func (x ApiKeyUsage) String() string {
	return proto.EnumName(ApiKeyUsage_name, int32(x))
}

func (ApiKeyUsage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_134ea681c61f9ca0, []int{2}
}

type EventType int32

const (
	EventType_USER_BLACKLISTED        EventType = 0
	EventType_ADD_USAGE_RECORD_FAILED EventType = 1
)

var EventType_name = map[int32]string{
	0: "USER_BLACKLISTED",
	1: "ADD_USAGE_RECORD_FAILED",
}

var EventType_value = map[string]int32{
	"USER_BLACKLISTED":        0,
	"ADD_USAGE_RECORD_FAILED": 1,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_134ea681c61f9ca0, []int{3}
}

type UserByIdRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserByIdRequest) Reset()         { *m = UserByIdRequest{} }
func (m *UserByIdRequest) String() string { return proto.CompactTextString(m) }
func (*UserByIdRequest) ProtoMessage()    {}
func (*UserByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_134ea681c61f9ca0, []int{0}
}

func (m *UserByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserByIdRequest.Unmarshal(m, b)
}
func (m *UserByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserByIdRequest.Marshal(b, m, deterministic)
}
func (m *UserByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserByIdRequest.Merge(m, src)
}
func (m *UserByIdRequest) XXX_Size() int {
	return xxx_messageInfo_UserByIdRequest.Size(m)
}
func (m *UserByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserByIdRequest proto.InternalMessageInfo

func (m *UserByIdRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ApiKeyByIdRequest struct {
	ApiKeyId             string   `protobuf:"bytes,1,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiKeyByIdRequest) Reset()         { *m = ApiKeyByIdRequest{} }
func (m *ApiKeyByIdRequest) String() string { return proto.CompactTextString(m) }
func (*ApiKeyByIdRequest) ProtoMessage()    {}
func (*ApiKeyByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_134ea681c61f9ca0, []int{1}
}

func (m *ApiKeyByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiKeyByIdRequest.Unmarshal(m, b)
}
func (m *ApiKeyByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiKeyByIdRequest.Marshal(b, m, deterministic)
}
func (m *ApiKeyByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiKeyByIdRequest.Merge(m, src)
}
func (m *ApiKeyByIdRequest) XXX_Size() int {
	return xxx_messageInfo_ApiKeyByIdRequest.Size(m)
}
func (m *ApiKeyByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiKeyByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiKeyByIdRequest proto.InternalMessageInfo

func (m *ApiKeyByIdRequest) GetApiKeyId() string {
	if m != nil {
		return m.ApiKeyId
	}
	return ""
}

type ApiKeyByKeyRequest struct {
	ApiKey               string   `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiKeyByKeyRequest) Reset()         { *m = ApiKeyByKeyRequest{} }
func (m *ApiKeyByKeyRequest) String() string { return proto.CompactTextString(m) }
func (*ApiKeyByKeyRequest) ProtoMessage()    {}
func (*ApiKeyByKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_134ea681c61f9ca0, []int{2}
}

func (m *ApiKeyByKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiKeyByKeyRequest.Unmarshal(m, b)
}
func (m *ApiKeyByKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiKeyByKeyRequest.Marshal(b, m, deterministic)
}
func (m *ApiKeyByKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiKeyByKeyRequest.Merge(m, src)
}
func (m *ApiKeyByKeyRequest) XXX_Size() int {
	return xxx_messageInfo_ApiKeyByKeyRequest.Size(m)
}
func (m *ApiKeyByKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiKeyByKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApiKeyByKeyRequest proto.InternalMessageInfo

func (m *ApiKeyByKeyRequest) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

type User struct {
	Id                     string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId             string               `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Email                  string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified          bool                 `protobuf:"varint,4,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	FirstName              string               `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName               string               `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Website                string               `protobuf:"bytes,7,opt,name=website,proto3" json:"website,omitempty"`
	CustomerId             string               `protobuf:"bytes,8,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	FavoriteChannel        string               `protobuf:"bytes,9,opt,name=favorite_channel,json=favoriteChannel,proto3" json:"favorite_channel,omitempty"`
	Disabled               bool                 `protobuf:"varint,10,opt,name=disabled,proto3" json:"disabled,omitempty"`
	SocialAccounts         []*SocialAccount     `protobuf:"bytes,11,rep,name=social_accounts,json=socialAccounts,proto3" json:"social_accounts,omitempty"`
	AppliedCoupons         []string             `protobuf:"bytes,12,rep,name=applied_coupons,json=appliedCoupons,proto3" json:"applied_coupons,omitempty"`
	FeatureFlags           []FeatureName        `protobuf:"varint,13,rep,packed,name=feature_flags,json=featureFlags,proto3,enum=dfuse.adminapi.v1.FeatureName" json:"feature_flags,omitempty"`
	DocumentQuota          int64                `protobuf:"varint,15,opt,name=document_quota,json=documentQuota,proto3" json:"document_quota,omitempty"`
	EffectiveDocumentQuota int64                `protobuf:"varint,16,opt,name=effective_document_quota,json=effectiveDocumentQuota,proto3" json:"effective_document_quota,omitempty"`
	PlanTier               PlanTier             `protobuf:"varint,17,opt,name=plan_tier,json=planTier,proto3,enum=dfuse.adminapi.v1.PlanTier" json:"plan_tier,omitempty"`
	DeletedAt              *timestamp.Timestamp `protobuf:"bytes,20,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CreatedAt              *timestamp.Timestamp `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              *timestamp.Timestamp `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}             `json:"-"`
	XXX_unrecognized       []byte               `json:"-"`
	XXX_sizecache          int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_134ea681c61f9ca0, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetEmailVerified() bool {
	if m != nil {
		return m.EmailVerified
	}
	return false
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *User) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *User) GetFavoriteChannel() string {
	if m != nil {
		return m.FavoriteChannel
	}
	return ""
}

func (m *User) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *User) GetSocialAccounts() []*SocialAccount {
	if m != nil {
		return m.SocialAccounts
	}
	return nil
}

func (m *User) GetAppliedCoupons() []string {
	if m != nil {
		return m.AppliedCoupons
	}
	return nil
}

func (m *User) GetFeatureFlags() []FeatureName {
	if m != nil {
		return m.FeatureFlags
	}
	return nil
}

func (m *User) GetDocumentQuota() int64 {
	if m != nil {
		return m.DocumentQuota
	}
	return 0
}

func (m *User) GetEffectiveDocumentQuota() int64 {
	if m != nil {
		return m.EffectiveDocumentQuota
	}
	return 0
}

func (m *User) GetPlanTier() PlanTier {
	if m != nil {
		return m.PlanTier
	}
	return PlanTier_FREE
}

func (m *User) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type SocialAccount struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Handle               string   `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialAccount) Reset()         { *m = SocialAccount{} }
func (m *SocialAccount) String() string { return proto.CompactTextString(m) }
func (*SocialAccount) ProtoMessage()    {}
func (*SocialAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_134ea681c61f9ca0, []int{4}
}

func (m *SocialAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialAccount.Unmarshal(m, b)
}
func (m *SocialAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialAccount.Marshal(b, m, deterministic)
}
func (m *SocialAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialAccount.Merge(m, src)
}
func (m *SocialAccount) XXX_Size() int {
	return xxx_messageInfo_SocialAccount.Size(m)
}
func (m *SocialAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialAccount.DiscardUnknown(m)
}

var xxx_messageInfo_SocialAccount proto.InternalMessageInfo

func (m *SocialAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SocialAccount) GetHandle() string {
	if m != nil {
		return m.Handle
	}
	return ""
}

type FeatureFlag struct {
	Name                 FeatureName `protobuf:"varint,1,opt,name=name,proto3,enum=dfuse.adminapi.v1.FeatureName" json:"name,omitempty"`
	Value                *any.Any    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FeatureFlag) Reset()         { *m = FeatureFlag{} }
func (m *FeatureFlag) String() string { return proto.CompactTextString(m) }
func (*FeatureFlag) ProtoMessage()    {}
func (*FeatureFlag) Descriptor() ([]byte, []int) {
	return fileDescriptor_134ea681c61f9ca0, []int{5}
}

func (m *FeatureFlag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureFlag.Unmarshal(m, b)
}
func (m *FeatureFlag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureFlag.Marshal(b, m, deterministic)
}
func (m *FeatureFlag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureFlag.Merge(m, src)
}
func (m *FeatureFlag) XXX_Size() int {
	return xxx_messageInfo_FeatureFlag.Size(m)
}
func (m *FeatureFlag) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureFlag.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureFlag proto.InternalMessageInfo

func (m *FeatureFlag) GetName() FeatureName {
	if m != nil {
		return m.Name
	}
	return FeatureName_WORKERS
}

func (m *FeatureFlag) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type ApiKey struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Usage                ApiKeyUsage          `protobuf:"varint,2,opt,name=usage,proto3,enum=dfuse.adminapi.v1.ApiKeyUsage" json:"usage,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId              string               `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ApiKey               string               `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Tier                 string               `protobuf:"bytes,6,opt,name=tier,proto3" json:"tier,omitempty"`
	StartBlock           int64                `protobuf:"varint,7,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	ValiditySecond       int64                `protobuf:"varint,8,opt,name=validity_second,json=validitySecond,proto3" json:"validity_second,omitempty"`
	Origin               string               `protobuf:"bytes,9,opt,name=origin,proto3" json:"origin,omitempty"`
	IpQuota              int64                `protobuf:"varint,15,opt,name=ip_quota,json=ipQuota,proto3" json:"ip_quota,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,20,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ApiKey) Reset()         { *m = ApiKey{} }
func (m *ApiKey) String() string { return proto.CompactTextString(m) }
func (*ApiKey) ProtoMessage()    {}
func (*ApiKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_134ea681c61f9ca0, []int{6}
}

func (m *ApiKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiKey.Unmarshal(m, b)
}
func (m *ApiKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiKey.Marshal(b, m, deterministic)
}
func (m *ApiKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiKey.Merge(m, src)
}
func (m *ApiKey) XXX_Size() int {
	return xxx_messageInfo_ApiKey.Size(m)
}
func (m *ApiKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiKey.DiscardUnknown(m)
}

var xxx_messageInfo_ApiKey proto.InternalMessageInfo

func (m *ApiKey) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApiKey) GetUsage() ApiKeyUsage {
	if m != nil {
		return m.Usage
	}
	return ApiKeyUsage_SERVER
}

func (m *ApiKey) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApiKey) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *ApiKey) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *ApiKey) GetTier() string {
	if m != nil {
		return m.Tier
	}
	return ""
}

func (m *ApiKey) GetStartBlock() int64 {
	if m != nil {
		return m.StartBlock
	}
	return 0
}

func (m *ApiKey) GetValiditySecond() int64 {
	if m != nil {
		return m.ValiditySecond
	}
	return 0
}

func (m *ApiKey) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *ApiKey) GetIpQuota() int64 {
	if m != nil {
		return m.IpQuota
	}
	return 0
}

func (m *ApiKey) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func (m *ApiKey) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ApiKey) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type ApiKeyInfo struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ApiKey               *ApiKey  `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiKeyInfo) Reset()         { *m = ApiKeyInfo{} }
func (m *ApiKeyInfo) String() string { return proto.CompactTextString(m) }
func (*ApiKeyInfo) ProtoMessage()    {}
func (*ApiKeyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_134ea681c61f9ca0, []int{7}
}

func (m *ApiKeyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiKeyInfo.Unmarshal(m, b)
}
func (m *ApiKeyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiKeyInfo.Marshal(b, m, deterministic)
}
func (m *ApiKeyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiKeyInfo.Merge(m, src)
}
func (m *ApiKeyInfo) XXX_Size() int {
	return xxx_messageInfo_ApiKeyInfo.Size(m)
}
func (m *ApiKeyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiKeyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ApiKeyInfo proto.InternalMessageInfo

func (m *ApiKeyInfo) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ApiKeyInfo) GetApiKey() *ApiKey {
	if m != nil {
		return m.ApiKey
	}
	return nil
}

type StoresEventRequest struct {
	Event                *Event   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoresEventRequest) Reset()         { *m = StoresEventRequest{} }
func (m *StoresEventRequest) String() string { return proto.CompactTextString(m) }
func (*StoresEventRequest) ProtoMessage()    {}
func (*StoresEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_134ea681c61f9ca0, []int{8}
}

func (m *StoresEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoresEventRequest.Unmarshal(m, b)
}
func (m *StoresEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoresEventRequest.Marshal(b, m, deterministic)
}
func (m *StoresEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoresEventRequest.Merge(m, src)
}
func (m *StoresEventRequest) XXX_Size() int {
	return xxx_messageInfo_StoresEventRequest.Size(m)
}
func (m *StoresEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoresEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoresEventRequest proto.InternalMessageInfo

func (m *StoresEventRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type StoresEventResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoresEventResponse) Reset()         { *m = StoresEventResponse{} }
func (m *StoresEventResponse) String() string { return proto.CompactTextString(m) }
func (*StoresEventResponse) ProtoMessage()    {}
func (*StoresEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_134ea681c61f9ca0, []int{9}
}

func (m *StoresEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoresEventResponse.Unmarshal(m, b)
}
func (m *StoresEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoresEventResponse.Marshal(b, m, deterministic)
}
func (m *StoresEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoresEventResponse.Merge(m, src)
}
func (m *StoresEventResponse) XXX_Size() int {
	return xxx_messageInfo_StoresEventResponse.Size(m)
}
func (m *StoresEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoresEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoresEventResponse proto.InternalMessageInfo

type Event struct {
	OwnerId              string               `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Type                 EventType            `protobuf:"varint,2,opt,name=type,proto3,enum=dfuse.adminapi.v1.EventType" json:"type,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Details              string               `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Data                 []byte               `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_134ea681c61f9ca0, []int{10}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_USER_BLACKLISTED
}

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Event) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Event) GetExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("dfuse.adminapi.v1.PlanTier", PlanTier_name, PlanTier_value)
	proto.RegisterEnum("dfuse.adminapi.v1.FeatureName", FeatureName_name, FeatureName_value)
	proto.RegisterEnum("dfuse.adminapi.v1.ApiKeyUsage", ApiKeyUsage_name, ApiKeyUsage_value)
	proto.RegisterEnum("dfuse.adminapi.v1.EventType", EventType_name, EventType_value)
	proto.RegisterType((*UserByIdRequest)(nil), "dfuse.adminapi.v1.UserByIdRequest")
	proto.RegisterType((*ApiKeyByIdRequest)(nil), "dfuse.adminapi.v1.ApiKeyByIdRequest")
	proto.RegisterType((*ApiKeyByKeyRequest)(nil), "dfuse.adminapi.v1.ApiKeyByKeyRequest")
	proto.RegisterType((*User)(nil), "dfuse.adminapi.v1.User")
	proto.RegisterType((*SocialAccount)(nil), "dfuse.adminapi.v1.SocialAccount")
	proto.RegisterType((*FeatureFlag)(nil), "dfuse.adminapi.v1.FeatureFlag")
	proto.RegisterType((*ApiKey)(nil), "dfuse.adminapi.v1.ApiKey")
	proto.RegisterType((*ApiKeyInfo)(nil), "dfuse.adminapi.v1.ApiKeyInfo")
	proto.RegisterType((*StoresEventRequest)(nil), "dfuse.adminapi.v1.StoresEventRequest")
	proto.RegisterType((*StoresEventResponse)(nil), "dfuse.adminapi.v1.StoresEventResponse")
	proto.RegisterType((*Event)(nil), "dfuse.adminapi.v1.Event")
}

func init() { proto.RegisterFile("dfuse/adminapi/v1/adminapi.proto", fileDescriptor_134ea681c61f9ca0) }

var fileDescriptor_134ea681c61f9ca0 = []byte{
	// 1293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x5d, 0x6e, 0xdb, 0x46,
	0x10, 0xb6, 0xfe, 0xa9, 0x91, 0x25, 0xd1, 0x5b, 0xc7, 0x66, 0x9c, 0xa4, 0x11, 0x84, 0xa6, 0x55,
	0x5d, 0x44, 0x6e, 0xd4, 0x3e, 0xb4, 0x0d, 0x10, 0x80, 0x92, 0xe8, 0x80, 0xb0, 0x2c, 0x39, 0xa4,
	0x9c, 0x14, 0x45, 0x01, 0x62, 0x25, 0xae, 0x9c, 0x45, 0x28, 0x92, 0xe1, 0x8f, 0x12, 0xdd, 0xa1,
	0x37, 0xe9, 0x01, 0xda, 0x63, 0xf4, 0xb1, 0xbd, 0x41, 0x8f, 0x51, 0xec, 0x2e, 0x29, 0xcb, 0xb6,
	0x5c, 0xa3, 0x8f, 0x7d, 0xdb, 0xf9, 0xf6, 0xfb, 0x66, 0x97, 0x9c, 0xf9, 0x86, 0x84, 0x86, 0x3d,
	0x8b, 0x43, 0x72, 0x84, 0xed, 0x39, 0x75, 0xb1, 0x4f, 0x8f, 0x16, 0xcf, 0x56, 0xeb, 0xb6, 0x1f,
	0x78, 0x91, 0x87, 0x76, 0x38, 0xa3, 0xbd, 0x42, 0x17, 0xcf, 0x0e, 0x1e, 0x5f, 0x78, 0xde, 0x85,
	0x43, 0x8e, 0x38, 0x61, 0x12, 0xcf, 0x8e, 0x22, 0x3a, 0x27, 0x61, 0x84, 0xe7, 0xbe, 0xd0, 0x1c,
	0xdc, 0xbf, 0x4e, 0xc0, 0xee, 0x52, 0x6c, 0x35, 0x0f, 0xa1, 0x7e, 0x1e, 0x92, 0xa0, 0xbb, 0xd4,
	0x6d, 0x83, 0xbc, 0x8f, 0x49, 0x18, 0xa1, 0x7d, 0x28, 0xc5, 0x21, 0x09, 0x2c, 0x6a, 0x2b, 0x99,
	0x46, 0xa6, 0x55, 0x36, 0x8a, 0x2c, 0xd4, 0xed, 0xe6, 0x33, 0xd8, 0x51, 0x7d, 0x7a, 0x42, 0x96,
	0xeb, 0xec, 0x87, 0x00, 0xd8, 0xa7, 0xd6, 0x3b, 0xb2, 0xbc, 0x14, 0x48, 0x98, 0xd3, 0x74, 0xbb,
	0xf9, 0x14, 0x50, 0x2a, 0x39, 0x21, 0xcb, 0xb5, 0x13, 0x12, 0x4d, 0x7a, 0x82, 0x10, 0x34, 0x7f,
	0x2b, 0x42, 0x9e, 0x5d, 0x07, 0xd5, 0x20, 0xbb, 0xca, 0x96, 0xa5, 0x36, 0x7a, 0x0c, 0x15, 0xf2,
	0x31, 0x22, 0x81, 0x8b, 0x1d, 0x76, 0x4c, 0x96, 0x6f, 0x40, 0x0a, 0xe9, 0x36, 0xda, 0x85, 0x02,
	0x99, 0x63, 0xea, 0x28, 0x39, 0xbe, 0x25, 0x02, 0xf4, 0x04, 0x6a, 0x7c, 0x61, 0x2d, 0x48, 0x40,
	0x67, 0x94, 0xd8, 0x4a, 0xbe, 0x91, 0x69, 0x49, 0x46, 0x95, 0xa3, 0xaf, 0x13, 0x10, 0x3d, 0x02,
	0x98, 0xd1, 0x20, 0x8c, 0x2c, 0x17, 0xcf, 0x89, 0x52, 0xe0, 0x19, 0xca, 0x1c, 0x19, 0xe2, 0x39,
	0x41, 0x0f, 0xa0, 0xec, 0xe0, 0x74, 0xb7, 0x28, 0x9e, 0x90, 0x01, 0x7c, 0x53, 0x81, 0xd2, 0x07,
	0x32, 0x09, 0x69, 0x44, 0x94, 0x12, 0xdf, 0x4a, 0x43, 0x76, 0xe7, 0x69, 0x1c, 0x46, 0xde, 0x5c,
	0xbc, 0x4b, 0x49, 0xdc, 0x39, 0x85, 0x74, 0x1b, 0x7d, 0x09, 0xf2, 0x0c, 0x2f, 0xbc, 0x80, 0x46,
	0xc4, 0x9a, 0xbe, 0xc5, 0xae, 0x4b, 0x1c, 0xa5, 0xcc, 0x59, 0xf5, 0x14, 0xef, 0x09, 0x18, 0x1d,
	0x80, 0x64, 0xd3, 0x10, 0x4f, 0x1c, 0x62, 0x2b, 0xc0, 0x1f, 0x61, 0x15, 0x23, 0x1d, 0xea, 0xa1,
	0x37, 0xa5, 0xd8, 0xb1, 0xf0, 0x74, 0xea, 0xc5, 0x6e, 0x14, 0x2a, 0x95, 0x46, 0xae, 0x55, 0xe9,
	0x34, 0xda, 0x37, 0x7a, 0xa5, 0x6d, 0x72, 0xa6, 0x2a, 0x88, 0x46, 0x2d, 0x5c, 0x0f, 0x43, 0xf4,
	0x05, 0xd4, 0xb1, 0xef, 0x3b, 0x94, 0xd8, 0xd6, 0xd4, 0x8b, 0x7d, 0xcf, 0x0d, 0x95, 0xed, 0x46,
	0xae, 0x55, 0x36, 0x6a, 0x09, 0xdc, 0x13, 0x28, 0xea, 0x41, 0x75, 0x46, 0x70, 0x14, 0x07, 0xc4,
	0x9a, 0x39, 0xf8, 0x22, 0x54, 0xaa, 0x8d, 0x5c, 0xab, 0xd6, 0xf9, 0x74, 0xc3, 0x89, 0xc7, 0x82,
	0xc7, 0x5e, 0x96, 0xb1, 0x9d, 0x88, 0x8e, 0x99, 0x86, 0x55, 0xc7, 0xf6, 0xa6, 0xf1, 0x9c, 0xb8,
	0x91, 0xf5, 0x3e, 0xf6, 0x22, 0xac, 0xd4, 0x1b, 0x99, 0x56, 0xce, 0xa8, 0xa6, 0xe8, 0x2b, 0x06,
	0xa2, 0xef, 0x40, 0x21, 0xb3, 0x19, 0x99, 0x46, 0x74, 0x41, 0xac, 0x6b, 0x02, 0x99, 0x0b, 0xf6,
	0x56, 0xfb, 0xfd, 0x6b, 0xca, 0xb2, 0xef, 0x60, 0xd7, 0x8a, 0x28, 0x09, 0x94, 0x9d, 0x46, 0xa6,
	0x55, 0xeb, 0x3c, 0xd8, 0x70, 0xc3, 0x33, 0x07, 0xbb, 0x63, 0x4a, 0x02, 0x43, 0xf2, 0x93, 0x15,
	0xfa, 0x1e, 0xc0, 0x26, 0x0e, 0x89, 0x88, 0x6d, 0xe1, 0x48, 0xd9, 0x6d, 0x64, 0x5a, 0x95, 0xce,
	0x41, 0x5b, 0xd8, 0xa8, 0x9d, 0xda, 0xa8, 0x3d, 0x4e, 0x7d, 0x66, 0x94, 0x13, 0xb6, 0x1a, 0x31,
	0xe9, 0x34, 0x20, 0x38, 0x91, 0xde, 0xbb, 0x5b, 0x9a, 0xb0, 0x85, 0x34, 0xf6, 0xed, 0x54, 0xba,
	0x77, 0xb7, 0x34, 0x61, 0xab, 0x51, 0xf3, 0x39, 0x54, 0xaf, 0x94, 0x16, 0x21, 0xc8, 0xf3, 0x7e,
	0x15, 0x1e, 0xe2, 0x6b, 0xb4, 0x07, 0xc5, 0xb7, 0xd8, 0xb5, 0x1d, 0x92, 0x18, 0x28, 0x89, 0x9a,
	0x73, 0xa8, 0x1c, 0x5f, 0x16, 0x06, 0x75, 0xd6, 0xa4, 0x77, 0xd7, 0x54, 0xa4, 0x3e, 0x84, 0xc2,
	0x02, 0x3b, 0xb1, 0xc8, 0x5c, 0xe9, 0xec, 0xde, 0xb8, 0xb5, 0xea, 0x2e, 0x0d, 0x41, 0x69, 0xfe,
	0x99, 0x83, 0xa2, 0x98, 0x0a, 0x37, 0x7c, 0xfe, 0x2d, 0x14, 0xe2, 0x10, 0x5f, 0x88, 0x34, 0x9b,
	0xcf, 0x16, 0xca, 0x73, 0xc6, 0x32, 0x04, 0x79, 0xf5, 0xac, 0xb9, 0xb5, 0x67, 0xbd, 0x0f, 0x92,
	0xf7, 0xc1, 0x15, 0xd6, 0xcb, 0x0b, 0x63, 0xf2, 0x58, 0xb7, 0xd7, 0xc7, 0x4f, 0x61, 0x7d, 0xfc,
	0xb0, 0x3c, 0xbc, 0x55, 0x84, 0xc7, 0xf9, 0x9a, 0xb9, 0x38, 0x8c, 0x70, 0x10, 0x59, 0x13, 0xc7,
	0x9b, 0xbe, 0xe3, 0x1e, 0xcf, 0x19, 0xc0, 0xa1, 0x2e, 0x43, 0x98, 0x67, 0x16, 0xd8, 0xa1, 0x36,
	0x8d, 0x96, 0x56, 0x48, 0xa6, 0x9e, 0x2b, 0xac, 0x9e, 0x33, 0x6a, 0x29, 0x6c, 0x72, 0x94, 0xbd,
	0x7d, 0x2f, 0xa0, 0x17, 0xd4, 0x4d, 0x4c, 0x9e, 0x44, 0xec, 0xa6, 0xd4, 0xbf, 0x62, 0x80, 0x12,
	0xf5, 0x45, 0x03, 0xff, 0xef, 0xda, 0x70, 0x0e, 0x20, 0xea, 0xa3, 0xbb, 0x33, 0x0f, 0x7d, 0x05,
	0x79, 0xf6, 0xe9, 0xe0, 0xf5, 0xad, 0x74, 0xf6, 0x37, 0x14, 0x93, 0x0d, 0x7b, 0x83, 0x93, 0x50,
	0xe7, 0xb2, 0x2a, 0xa2, 0x87, 0xee, 0xdf, 0x5a, 0xfc, 0xd5, 0xf7, 0xa2, 0x0f, 0xc8, 0x8c, 0xbc,
	0x80, 0x84, 0xda, 0x82, 0xb8, 0x51, 0xfa, 0x79, 0x69, 0x43, 0x81, 0xb0, 0x38, 0xc9, 0xa3, 0x6c,
	0xc8, 0x23, 0xf8, 0x82, 0xd6, 0xbc, 0x07, 0x9f, 0x5c, 0xc9, 0x12, 0xb2, 0x11, 0x47, 0x9a, 0xbf,
	0x64, 0xa1, 0xc0, 0x91, 0x2b, 0xbd, 0x94, 0xb9, 0xda, 0x4b, 0x5f, 0x43, 0x3e, 0x5a, 0xfa, 0x69,
	0xbf, 0x3e, 0xbc, 0xed, 0xa8, 0xf1, 0xd2, 0x27, 0x06, 0x67, 0x6e, 0x6c, 0x56, 0x05, 0x4a, 0x36,
	0x89, 0x30, 0x75, 0xc2, 0xb4, 0x57, 0x93, 0xf0, 0x5a, 0x19, 0x0b, 0xff, 0xb1, 0x8c, 0xe4, 0xa3,
	0x4f, 0x03, 0x12, 0x32, 0x69, 0xf1, 0x6e, 0x69, 0xc2, 0x56, 0xf9, 0xf0, 0xb0, 0x71, 0x84, 0x79,
	0xb7, 0x6f, 0x1b, 0x7c, 0x7d, 0xf8, 0x02, 0xa4, 0x74, 0x50, 0x22, 0x09, 0xf2, 0xc7, 0x86, 0xa6,
	0xc9, 0x5b, 0x48, 0x82, 0xdc, 0x99, 0x31, 0x92, 0xff, 0x2e, 0xa1, 0x2a, 0x48, 0xdd, 0x73, 0x53,
	0x1f, 0x6a, 0xa6, 0x29, 0xff, 0x51, 0x47, 0x75, 0x00, 0x6d, 0x38, 0xd6, 0x8c, 0x33, 0x43, 0x37,
	0x35, 0xf9, 0xf7, 0xfd, 0xc3, 0x5f, 0x33, 0xab, 0x29, 0xc3, 0x3f, 0x9c, 0x75, 0x28, 0xbd, 0x19,
	0x19, 0x27, 0x9a, 0x61, 0xca, 0x5b, 0x07, 0x59, 0x29, 0x83, 0x6a, 0x50, 0x1c, 0xbf, 0xd1, 0x07,
	0xfa, 0x48, 0xce, 0xf0, 0xb8, 0x04, 0x39, 0x75, 0x30, 0x90, 0xb3, 0x08, 0x41, 0x4d, 0xfb, 0x71,
	0x6c, 0xa8, 0xd6, 0x50, 0x1b, 0x33, 0x89, 0x29, 0xe7, 0xd0, 0x1e, 0xa0, 0xd1, 0xd0, 0xea, 0x6b,
	0xa7, 0xea, 0xb0, 0x7f, 0x89, 0xe7, 0xd1, 0x1e, 0xd4, 0x7a, 0xe7, 0xe6, 0x78, 0x74, 0x6a, 0xa5,
	0xc9, 0x0b, 0x3c, 0x59, 0x15, 0xca, 0xe3, 0xd1, 0x89, 0x36, 0x3c, 0xd5, 0xc6, 0xaa, 0x5c, 0x44,
	0xdb, 0x20, 0x75, 0x07, 0xa3, 0xde, 0x89, 0x7a, 0xa6, 0xcb, 0x25, 0xb4, 0x03, 0x55, 0x9d, 0xdd,
	0x75, 0xa8, 0x0e, 0x2c, 0x6d, 0x64, 0xbe, 0x92, 0xa5, 0xc3, 0x1f, 0xa0, 0xb2, 0x36, 0x68, 0x10,
	0x40, 0xd1, 0xd4, 0x8c, 0xd7, 0x9a, 0x21, 0x6f, 0xb1, 0x7b, 0xbd, 0xd1, 0xba, 0x72, 0x86, 0x81,
	0xa7, 0xa3, 0xae, 0x3e, 0xd0, 0xe4, 0x2c, 0x5b, 0x8b, 0x03, 0xe5, 0xdc, 0xe1, 0x0b, 0x28, 0xaf,
	0x8a, 0x8e, 0x76, 0x41, 0x3e, 0x37, 0x35, 0xc3, 0xea, 0x0e, 0xd4, 0xde, 0xc9, 0x40, 0x37, 0xc7,
	0x5a, 0x5f, 0xde, 0x42, 0x0f, 0x60, 0x5f, 0xed, 0xf7, 0xad, 0x73, 0x53, 0x7d, 0xa9, 0x59, 0x86,
	0xd6, 0x1b, 0x19, 0x7d, 0xeb, 0x58, 0xd5, 0x07, 0x5a, 0x5f, 0xce, 0x74, 0xfe, 0xca, 0x82, 0xa4,
	0xb2, 0x0e, 0x52, 0x7d, 0x8a, 0x5e, 0x82, 0x94, 0xfe, 0xa0, 0xa1, 0xe6, 0x2d, 0x0e, 0x5a, 0xfb,
	0x1f, 0x3b, 0xb8, 0xcd, 0x65, 0xe8, 0x55, 0x6a, 0x4d, 0x9e, 0xea, 0xb3, 0x5b, 0xcd, 0xb5, 0x9e,
	0xec, 0xd1, 0xad, 0x2c, 0xee, 0x6f, 0x33, 0x7d, 0x49, 0xfc, 0xef, 0x0e, 0x3d, 0xf9, 0x97, 0x9c,
	0x97, 0x7f, 0x7f, 0x77, 0x25, 0xfd, 0x19, 0x2a, 0x6b, 0x6e, 0xdc, 0x98, 0xf4, 0xa6, 0xe7, 0x0f,
	0x3e, 0xbf, 0x8b, 0x26, 0x4c, 0xdd, 0xd5, 0x7e, 0xea, 0x5d, 0xd0, 0xe8, 0x6d, 0x3c, 0x69, 0x4f,
	0xbd, 0xf9, 0x11, 0xd7, 0x3c, 0xa5, 0x5e, 0xb2, 0x08, 0x31, 0x0e, 0x9f, 0xfa, 0x01, 0x5d, 0x1c,
	0xf9, 0x93, 0xa3, 0x1b, 0x7f, 0xe2, 0xcf, 0xfd, 0x49, 0x1a, 0x4d, 0x8a, 0xdc, 0x3f, 0xdf, 0xfc,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x32, 0x22, 0x72, 0x26, 0xb0, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminApiClient is the client API for AdminApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminApiClient interface {
	UserById(ctx context.Context, in *UserByIdRequest, opts ...grpc.CallOption) (*User, error)
	ApiKeyById(ctx context.Context, in *ApiKeyByIdRequest, opts ...grpc.CallOption) (*ApiKeyInfo, error)
	ApiKeyByKey(ctx context.Context, in *ApiKeyByKeyRequest, opts ...grpc.CallOption) (*ApiKeyInfo, error)
	StoresEvent(ctx context.Context, in *StoresEventRequest, opts ...grpc.CallOption) (*StoresEventResponse, error)
}

type adminApiClient struct {
	cc *grpc.ClientConn
}

func NewAdminApiClient(cc *grpc.ClientConn) AdminApiClient {
	return &adminApiClient{cc}
}

func (c *adminApiClient) UserById(ctx context.Context, in *UserByIdRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/dfuse.adminapi.v1.AdminApi/UserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminApiClient) ApiKeyById(ctx context.Context, in *ApiKeyByIdRequest, opts ...grpc.CallOption) (*ApiKeyInfo, error) {
	out := new(ApiKeyInfo)
	err := c.cc.Invoke(ctx, "/dfuse.adminapi.v1.AdminApi/ApiKeyById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminApiClient) ApiKeyByKey(ctx context.Context, in *ApiKeyByKeyRequest, opts ...grpc.CallOption) (*ApiKeyInfo, error) {
	out := new(ApiKeyInfo)
	err := c.cc.Invoke(ctx, "/dfuse.adminapi.v1.AdminApi/ApiKeyByKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminApiClient) StoresEvent(ctx context.Context, in *StoresEventRequest, opts ...grpc.CallOption) (*StoresEventResponse, error) {
	out := new(StoresEventResponse)
	err := c.cc.Invoke(ctx, "/dfuse.adminapi.v1.AdminApi/StoresEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminApiServer is the server API for AdminApi service.
type AdminApiServer interface {
	UserById(context.Context, *UserByIdRequest) (*User, error)
	ApiKeyById(context.Context, *ApiKeyByIdRequest) (*ApiKeyInfo, error)
	ApiKeyByKey(context.Context, *ApiKeyByKeyRequest) (*ApiKeyInfo, error)
	StoresEvent(context.Context, *StoresEventRequest) (*StoresEventResponse, error)
}

// UnimplementedAdminApiServer can be embedded to have forward compatible implementations.
type UnimplementedAdminApiServer struct {
}

func (*UnimplementedAdminApiServer) UserById(ctx context.Context, req *UserByIdRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserById not implemented")
}
func (*UnimplementedAdminApiServer) ApiKeyById(ctx context.Context, req *ApiKeyByIdRequest) (*ApiKeyInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApiKeyById not implemented")
}
func (*UnimplementedAdminApiServer) ApiKeyByKey(ctx context.Context, req *ApiKeyByKeyRequest) (*ApiKeyInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApiKeyByKey not implemented")
}
func (*UnimplementedAdminApiServer) StoresEvent(ctx context.Context, req *StoresEventRequest) (*StoresEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoresEvent not implemented")
}

func RegisterAdminApiServer(s *grpc.Server, srv AdminApiServer) {
	s.RegisterService(&_AdminApi_serviceDesc, srv)
}

func _AdminApi_UserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminApiServer).UserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.adminapi.v1.AdminApi/UserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminApiServer).UserById(ctx, req.(*UserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminApi_ApiKeyById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiKeyByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminApiServer).ApiKeyById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.adminapi.v1.AdminApi/ApiKeyById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminApiServer).ApiKeyById(ctx, req.(*ApiKeyByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminApi_ApiKeyByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiKeyByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminApiServer).ApiKeyByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.adminapi.v1.AdminApi/ApiKeyByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminApiServer).ApiKeyByKey(ctx, req.(*ApiKeyByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminApi_StoresEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoresEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminApiServer).StoresEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dfuse.adminapi.v1.AdminApi/StoresEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminApiServer).StoresEvent(ctx, req.(*StoresEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dfuse.adminapi.v1.AdminApi",
	HandlerType: (*AdminApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserById",
			Handler:    _AdminApi_UserById_Handler,
		},
		{
			MethodName: "ApiKeyById",
			Handler:    _AdminApi_ApiKeyById_Handler,
		},
		{
			MethodName: "ApiKeyByKey",
			Handler:    _AdminApi_ApiKeyByKey_Handler,
		},
		{
			MethodName: "StoresEvent",
			Handler:    _AdminApi_StoresEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dfuse/adminapi/v1/adminapi.proto",
}
